### ISSUE TITLE
get error when trying to access library(fitbitr)

### ISSUE THREAD

**Issue by sportsfreund1** [Avsecz/fitbitr#1]
Hey Avsecz.

Thanks for publishing this great code.

I'm a really beginner in R und trying to run the fitbitr. 
Unfortunately I have problems with accessing the library and go for further steps.

When I type library(fitbitr) the following error message appears:
`Error in parse(n = -1, file = file, srcfile = NULL, keep.source = FALSE) : 
  30:4: unexpected symbol
29: MyAppName
30: 123X45`

And there's a caret ^ pointing on the "X" of my OAuth 2.0 Client ID

`Error : can't load R programme code in package ‘fitbitr’
Error: failed to load namespace for "fitbitr" from package`

I guess there's an easy solution for this problem. I would be glad to get some hints for that. 

Best 
Sportsfreund1

**Comment by Avsecz** [comment]
Installation works fine for me on R 3.2.2: 

```
> devtools::install_github("avsecz/fitbitr")
Downloading GitHub repo avsecz/fitbitr@master
from URL https://api.github.com/repos/avsecz/fitbitr/zipball/master
Installing fitbitr
'/opt/modules/i12g/R/3.3.2-Bioc3.4/lib64/R/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpDsUUkE/devtools7854727ead87/Avsecz-fitbitr-c0231ee'  \
  --library='/data/nasif12/modules_if12/SL7/i12g/R/3.3.2-Bioc3.4/lib64/R/library'  \
  --install-tests 

* installing *source* package ‘fitbitr’ ...
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (fitbitr)
> library(fitbitr)
> fitbitr::
fitbitr::rate_limit              fitbitr::fitbit_GET              fitbitr::get_fitbit_token
fitbitr::activity_features_info  fitbitr::get_activity            fitbitr::fitbit_parse
fitbitr::activity_features       fitbitr::refresh_fitbit_token    
> fitbitr::fitbit_GET
function (path, token, ...) 
{
    req <- GET("https://api.fitbit.com", path = path, config = config(token = token))
    fitbit_check(req)
    attr(token, "rate_limit") <- extract_rate_limit(req)
    req
}
<environment: namespace:fitbitr>
> 
```

Try installing the app by starting R with the following command: `R --vanilla` and then paste the installation output together with the output of `sessionInfo()`.

Best
Ziga

**Comment by sportsfreund1** [comment]
Hey Ziga.

Thanks for the quick answer. 

When I start R --vanilla and try to install it: 

```
devtools::install_github("avsecz/fitbitr")
Skipping install of 'fitbitr' from a github remote, the SHA1 (c0231eef) has not changed since last install.
  Use `force = TRUE` to force installation
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 10240)

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C
[5] LC_TIME=German_Germany.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] httr_1.2.1      R6_2.2.0        withr_1.0.2     curl_2.3
[5] memoise_1.0.0   git2r_0.18.0    digest_0.6.12   devtools_1.12.0
```

**Comment by sportsfreund1** [comment]
Hey Ziga,

thanks for this quick answer. 

I got it. It's not working with reading the fitbitr-file but with manual input of the credentials. 

`Waiting for authentication in browser...`

And in the browser I get the following error:
> Developer information: invalid_request - Invalid redirect_uri parameter value

I get a step further when I use "**OAuth 2.0 tutorial page**". Then I come through an get a browser message: "Authentication complete. Please close this page and return to R."


But when I go back to R it says: 

`Error: Authentication failed.`
Using the Implicit Grant Flow

or

```
Authentication complete.
Error in init_oauth2.0(self$endpoint, self$app, scope = self$params$scope,  : 
  Bad Request (HTTP 400). Failed to get an access token.
```
Using the Authorization Code Flow

**Comment by Avsecz** [comment]
hm. Have you created an account on fitbit developer & registred the app? 

It could be that the API has changed since I developed the package. I might have a look.

**Comment by sportsfreund1** [comment]
Yep I did. And I used all the settings you used in your documentation. 

Thanks! Let me know if you found the problem! 

Best 
Tino

**Comment by sportsfreund1** [comment]
Hey Ziga.

I know tried it another time on a different system. Same Same. 

Best 
Tino

**Comment by sportsfreund1** [comment]
Hey Ziga. 

Sorry for beeing a little bit annoying with this topic. 
I've a recent research project and since it seemes to be very great I would like to use your code for accessing the data. 

Is there any solution for this problem? 

Best 
Tino

**Comment by Avsecz** [comment]
Hey Tino,

I'm currently quite busy and would like to prevent work duplication - there seem to be quite a few libraries out there that do a similar job. Have you checked out the following libraries?

- https://github.com/teramonagi/fitbitr
- https://github.com/orcasgit/python-fitbit

What features are they lacking that fitbitr offers?

**Comment by sportsfreund1** [comment]
Hej Ziga.

Same for me.
Thanks for the recommendations. Unfortunately the fitbitr from teramonagi
has the same outcome.

And i can't really find the problem.
​Trying to do some requests over OAuth 2.0 tutorial page
<https://dev.fitbit.com/apps/oauthinteractivetutorial?clientEncodedId=228J4H&clientSecret=ef666d670b2f9f46127aac38dd0e25f3&redirectUri=http://localhost:1410&applicationType=PERSONAL>
works pretty fine.

Best
Tino​
​

2017-04-10 11:26 GMT+02:00 Žiga Avsec <notifications@github.com>:

**Comment by Avsecz** [comment]
Hey, @sportsfreund1 see the solution of https://github.com/Avsecz/fitbitr/issues/2. It now works for me as well. closing the issue.
